### ISSUE TITLE
How I get the wiegand code

### ISSUE THREAD

**Issue by theorangewill** [paulo-raca/YetAnotherArduinoWiegandLibrary#8]
Hey,

Maybe it is a dumb question. But my RFIDcard has three numbers: 

> W: 077,30211
> S: 0A004D7603
> A: 0042954749443

Which i think they are  Wiegand 26Bits, Abatrack II e RS232 codes, respectively.
The library takes the S code, but I want to get W code.

Thanks

**Comment by paulo-raca** [comment]
They are all the same number, just written differently.
I have no idea why they would do that, it is annoying and confusing :man_shrugging: 

The `S` number is hexadecimal representation of the number on the card.
The `A` number is the same, but in decimal (0x0A004D7603 = 42954749443)
The `W` number is completely stupid: The 3rd byte in decimal (0x4D = 77), comma, 4th and 5th bytes in decimal (0x7603 = 30211)

When working with Wiegand I suggest you only use the hexadecimal representation, because:
- The `W` representation is just stupid :man_facepalming: 
- Wiegand truncates the codes to 3 or 4 bytes. While you can easily see that the numbers match in hexadecimal, they seem completely unrelated in decimal (0x0A004D7603 = 42954749443, but 0x4D7603 = 5076483)
